### ISSUE TITLE
AD admin's password in plain text

### ISSUE THREAD

**Issue by LinguineCode** [ajjahn/puppet-samba#31]
Obviously a problem. At least chmod 770 the file or something, before we can find a better solution.

**Comment by stephencooke** [comment]
is this still an open issue?

**Comment by seanscottking** [comment]
Hey @stephencooke, it's been a while, but I just checked the code and the problem seems to still exist here: https://github.com/ajjahn/puppet-samba/blob/master/templates/configure_active_directory.erb#L57
