### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mbrodala** [ajjahn/puppet-samba#36]
The last release is from April 2014 and in the meantime [a lot of stuff](https://github.com/ajjahn/puppet-samba/compare/v0.2.0...ccd3b424be3edb29c5576dbbbcf1ec2fa9e8ed88) has happened.

Thus please release a new version.

**Comment by ajjahn** [comment]
Better [late](https://forge.puppetlabs.com/ajjahn/samba) than never??? I'm working on getting some basic test coverage in place to make it easier to release faster.

**Comment by mbrodala** [comment]
Thanks. :-)
