### ISSUE TITLE
samba service name on Debian 8

### ISSUE THREAD

**Issue by rotulet** [ajjahn/puppet-samba#47]
Hi,
on debian 8 with samba  2:4.1.21+dfsg-2+b2, the service name is now *smbd* and not *samba*. This generate the following error:

    Error: Could not start Service[samba]: Execution of '/usr/sbin/service samba start' returned 1: Failed to start samba.service: Unit samba.service is masked.
    Error: /Stage[main]/Samba::Server::Service/Service[samba]/ensure: change from stopped to running failed: Could not start Service[samba]: Execution of '/usr/sbin/service samba start' returned 1: Failed to start samba.service: Unit samba.service is masked.

See https://github.com/thias/puppet-samba/pull/18

Thanks,
Rot.

**Comment by rotulet** [comment]
Great!
May I suggest to create a release for the puppet forge?
Thanks!

**Comment by ajjahn** [comment]
Released: [0.4.0](https://forge.puppetlabs.com/ajjahn/samba/0.4.0).
