### ISSUE TITLE
Exec[add smb account for myuser]/returns: sudoers: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by alexjfisher** [ajjahn/puppet-samba#48]
Hi

I'm not sure that the 'sudo' in https://github.com/ajjahn/puppet-samba/blob/master/templates/add_samba_user#L7 is necessary.  Puppet almost always will be running as root and the rest of the module requires it to be.

Would you accept a PR removing the use of sudo?

Alternatively, couldn't the pbedit command not just be called from https://github.com/ajjahn/puppet-samba/blob/master/manifests/server/user.pp#L7 directly?

If you do still need add_samba_user and check_samba_user scripts installing (for use outside of puppet), they should probably be moved to the 'files' directory as they're not actually templates.

Kind Regards,
Alex

**Comment by ajjahn** [comment]
@alexjfisher I'd gladly accept a PR removing the need for sudo. Even better would be removing the need for the shell scripts all together. Yep, you're right, the scripts are files.

**Comment by alexjfisher** [comment]
@ajjahn Ok. I'll get on it.  If you're not using the scripts for anything else, I'll rip them out completely.

Thanks for the prompt reply!

**Comment by ajjahn** [comment]
@alexjfisher Great! By the way, this might be a good time to make sure tests are covering the behavior in question.
