### ISSUE TITLE
failing to join the domain RH6.x 

### ISSUE THREAD

**Issue by brettswift** [ajjahn/puppet-samba#77]
I'm using this module to join a linux box to the domain.   We don't yet have a requirement to set up shares,  we just want to have it on the domain so we can enable logins to the box.

The thought is coupling this with the SSSD module on a RHEL 6.4 machine. 

My knowledge of how Linux and Windows pair up is a bit limited, but I think I'm on the right path.   We've also successfully done this manually using `kinit` and `net ads join`. 

My question here is,  the `/sbin/configure_active_directory` file seems to have some issues. 

1.  `kinit` happens after `net ads join`.    We couldn't get this to work in that order. 
2. the `net ads join` command fails.  It puts two single quotes around the `createcomputer= ~OU` section.   If I take those single quotes out and run the command manually it works.  (however I have to run the kinit command first. 

I'm hoping someone can clarify if there's something I'm missing here, or if I've actually found a bug in this module. 

Thanks

**Comment by brettswift** [comment]
Any help? Should this module do what I'm expecting it to do?  Or are there some obvious domain configurations that make this incompatible?

**Comment by brettswift** [comment]
I might be able to use a different module but I'll drop this here in case it helps. 

http://serverfault.com/questions/597219/net-ads-join-fails-in-puppet-exec-but-runs-ok-directly-from-command-line

That suggests this might be an environment variable problem however I haven't tested it.

**Comment by ajjahn** [comment]
@brettswift Unfortunately, my knowledge of how Linux and Windows pair up is also a bit limited. @abraham1901 did most of the active directory implementation. Perhaps @abraham1901 could chime in on this one.
